-- ****** Objeto: Tabla MAIPOGRANDE.CLIENTEEXTERNO Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."CLIENTEEXTERNO" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBREEMPRESA" VARCHAR2(100) NOT NULL ENABLE,
	"PAIS" NUMBER(*,0) NOT NULL ENABLE,
	"CIUDAD" VARCHAR2(100),
	CONSTRAINT "CLIENTEEXTERNO_PK" PRIMARY KEY ("IDUSUARIO") ENABLE,
	CONSTRAINT "CLIENTEEXTERNO_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."USUARIO" ("IDUSUARIO") ENABLE
   );