-- ****** Objeto: Tabla MAIPOGRANDE.PERFIL Fecha de Script: 30-09-2020 20:40:59 ******
  CREATE TABLE "MAIPOGRANDE"."PERFIL" 
   (	"IDPERFIL" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBREPERFIL" VARCHAR2(50) NOT NULL ENABLE,
	"CODIGOPERFIL" VARCHAR2(20) NOT NULL ENABLE,
	"SERVICIOPERFIL" VARCHAR2(3) NOT NULL ENABLE,
	"ESTADO" NUMBER(1,0) NOT NULL ENABLE,
	CONSTRAINT "PERFIL_PK" PRIMARY KEY ("IDPERFIL") ENABLE
   );