-- ****** Objeto: Tabla MAIPOGRANDE.CAMION Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."CAMION" 
   (	"IDCAMION" NUMBER(*,0) NOT NULL ENABLE,
	"PESOMAXIMO" NUMBER(*,0),
	"REFRIGERA" CHAR(1) NOT NULL ENABLE,
	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "CAMION_PK" PRIMARY KEY ("IDCAMION") ENABLE,
	CONSTRAINT "CAMION_TRANSPORTISTA_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."TRANSPORTISTA" ("IDUSUARIO") ENABLE
   );