-- ****** Objeto: Tabla MAIPOGRANDE.OFERTA Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."OFERTA" 
   (	"IDOFERTA" NUMBER(*,0) NOT NULL ENABLE,
	"CANTIDAD" NUMBER(*,0) NOT NULL ENABLE,
	"VALORUNITARIO" NUMBER(*,0) NOT NULL ENABLE,
	"IDPROCESO" NUMBER(*,0) NOT NULL ENABLE,
	"ESTADO" VARCHAR2(10) NOT NULL ENABLE,
	"FECHAOFERTA" DATE NOT NULL ENABLE,
	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"IDPRODUCTO" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "OFERTA_PK" PRIMARY KEY ("IDOFERTA") ENABLE,
	CONSTRAINT "OFERTA_PROCESO_FK" FOREIGN KEY ("IDPROCESO")
	 REFERENCES "MAIPOGRANDE"."PROCESO" ("IDPROCESO") ENABLE,
	CONSTRAINT "OFERTA_PRODUCTO_FK" FOREIGN KEY ("IDPRODUCTO")
	 REFERENCES "MAIPOGRANDE"."PRODUCTO" ("IDPRODUCTO") ENABLE,
	CONSTRAINT "OFERTA_PRODUCTOR_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."PRODUCTOR" ("IDUSUARIO") ENABLE
   );