-- ****** Objeto: Tabla MAIPOGRANDE.LOGTRACE Fecha de Script: 22-09-2020 12:45:25 ******
  CREATE TABLE "MAIPOGRANDE"."LOGTRACE" 
   (	
    "LOGID" NUMBER(*,0) NOT NULL ENABLE,
	"IDSESSION" VARCHAR2(100) NOT NULL ENABLE,
	"SERVICIO" VARCHAR2(100) NOT NULL ENABLE,
	"SUBSERVICIO" VARCHAR2(100) NOT NULL ENABLE,
	"ENTRADA" CLOB NOT NULL ENABLE,
	"SALIDA" CLOB,
	"FECHA" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL ENABLE,
	"ESTADO" VARCHAR2(10) NOT NULL ENABLE,
	CONSTRAINT "LOGTRACE_PK" PRIMARY KEY ("LOGID") ENABLE
   );