-- ****** Objeto: Tabla MAIPOGRANDE.PRODUCTOR Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."PRODUCTOR" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"FIRMACONTRATO" CHAR(1) NOT NULL ENABLE,
	"FECHATERMINO" DATE NOT NULL ENABLE,
	"NOMBREPRODUCTOR" VARCHAR2(100) NOT NULL ENABLE,
	"RUTPRODUCTOR" VARCHAR2(20) NOT NULL ENABLE,
	"PERMITESALDOS" CHAR(1),
	"IDCOMUNA" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "PRODUCTOR_PK" PRIMARY KEY ("IDUSUARIO") ENABLE,
	CONSTRAINT "PRODUCTOR_COMUNA_FK" FOREIGN KEY ("IDCOMUNA")
	 REFERENCES "MAIPOGRANDE"."COMUNA" ("IDCOMUNA") ENABLE,
	CONSTRAINT "PRODUCTOR_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."USUARIO" ("IDUSUARIO") ENABLE
   );