-- ****** Objeto: Tabla MAIPOGRANDE.PRODUCTO Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."PRODUCTO" 
   (	"IDPRODUCTO" NUMBER(*,0) NOT NULL ENABLE,
	"CODIGOPRODUCTO" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(1000) NOT NULL ENABLE,
	"STOCK" NUMBER(*,0) NOT NULL ENABLE,
	"VALORUNITARIO" NUMBER(*,0) NOT NULL ENABLE,
	"TIPOVENTA" VARCHAR2(10) NOT NULL ENABLE,
	"CALIDAD" NUMBER(*,0) NOT NULL ENABLE,
	"FECHACADUCIDAD" DATE NOT NULL ENABLE,
	"FECHACREACION" DATE NOT NULL ENABLE,
	"FECHAMODIFICACION" DATE,
	"IDCATEGORIA" NUMBER(*,0) NOT NULL ENABLE,
	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("IDPRODUCTO") ENABLE,
	CONSTRAINT "PRODUCTO_CATEGORIA_FK" FOREIGN KEY ("IDCATEGORIA")
	 REFERENCES "MAIPOGRANDE"."CATEGORIA" ("IDCATEGORIA") ENABLE,
	CONSTRAINT "PRODUCTO_PRODUCTOR_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."PRODUCTOR" ("IDUSUARIO") ENABLE
   );