-- ****** Objeto: Tabla MAIPOGRANDE.PERFILMENU Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."PERFILMENU" 
   (	"IDPERFIL" NUMBER(*,0) NOT NULL ENABLE,
	"IDMENU" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "PERFILMENU_PK" PRIMARY KEY ("IDPERFIL","IDMENU") ENABLE,
	CONSTRAINT "PERFILMENU_MENU_FK" FOREIGN KEY ("IDMENU")
	 REFERENCES "MAIPOGRANDE"."MENU" ("IDMENU") ENABLE,
	CONSTRAINT "PERFILMENU_PERFIL_FK" FOREIGN KEY ("IDPERFIL")
	 REFERENCES "MAIPOGRANDE"."PERFIL" ("IDPERFIL") ENABLE
   );