-- ****** Objeto: Tabla MAIPOGRANDE.LOGTRACE Fecha de Script: 07-10-2020 21:52:07 ******
  CREATE TABLE "MAIPOGRANDE"."LOGTRACE" 
   (	"LOGID" NUMBER(*,0) NOT NULL ENABLE,
	"SERVICIO" VARCHAR2(100) NOT NULL ENABLE,
	"SUBSERVICIO" VARCHAR2(100) NOT NULL ENABLE,
	"ENTRADA" CLOB NOT NULL ENABLE,
	"SALIDA" CLOB NOT NULL ENABLE,
	"FECHA" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ESTADO" VARCHAR2(10) NOT NULL ENABLE,
	"IDSESION" VARCHAR2(100) NOT NULL ENABLE,
	CONSTRAINT "LOGTRACE_PK" PRIMARY KEY ("LOGID") ENABLE,
	CONSTRAINT "LOGTRACE_SESION_FK" FOREIGN KEY ("IDSESION")
	 REFERENCES "MAIPOGRANDE"."SESION" ("IDSESION") ENABLE
   );