-- ****** Objeto: Tabla MAIPOGRANDE.USUARIO Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."USUARIO" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"RUT" VARCHAR2(20) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(50) NOT NULL ENABLE,
	"APELLIDO" VARCHAR2(50) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE,
	"ESTADO" CHAR(1) NOT NULL ENABLE,
	"ACTIVO" CHAR(1) NOT NULL ENABLE,
	"DIRECCION" VARCHAR2(100) NOT NULL ENABLE,
	"CLAVE" VARCHAR2(100) NOT NULL ENABLE,
	"INTENTOS" NUMBER(1,0),
	"CAMBIACLAVE" CHAR(1),
	"FECHACREACION" DATE NOT NULL ENABLE,
	"FECHAMODIFICACION" DATE,
	"IDPERFIL" NUMBER(*,0) NOT NULL ENABLE,
	"TELEFONO" VARCHAR2(20) NOT NULL ENABLE,
	CONSTRAINT "USUARIO_PK" PRIMARY KEY ("IDUSUARIO") ENABLE,
	CONSTRAINT "USUARIO_PERFIL_FK" FOREIGN KEY ("IDPERFIL")
	 REFERENCES "MAIPOGRANDE"."PERFIL" ("IDPERFIL") ENABLE
   );