-- ****** Objeto: Tabla MAIPOGRANDE.ADMINISTRADOR Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."ADMINISTRADOR" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"IDCOMUNA" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "ADMINISTRADOR_PK" PRIMARY KEY ("IDUSUARIO") ENABLE,
	CONSTRAINT "ADMINISTRADOR_COMUNA_FK" FOREIGN KEY ("IDCOMUNA")
	 REFERENCES "MAIPOGRANDE"."COMUNA" ("IDCOMUNA") ENABLE,
	CONSTRAINT "ADMINISTRADOR_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."USUARIO" ("IDUSUARIO") ENABLE
   );