-- ****** Objeto: Tabla MAIPOGRANDE.ETAPA Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."ETAPA" 
   (	"IDETAPA" NUMBER(*,0) NOT NULL ENABLE,
	"ESTADOETAPA" VARCHAR2(50) NOT NULL ENABLE,
	"FECHAETAPA" DATE NOT NULL ENABLE,
	"IDPROCESO" NUMBER(*,0) NOT NULL ENABLE,
	"OBSERVACION" VARCHAR2(500),
	"ID" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "ETAPA_PK" PRIMARY KEY ("IDETAPA") ENABLE,
	CONSTRAINT "ETAPA_CONFIGURACION_FK" FOREIGN KEY ("ID")
	 REFERENCES "MAIPOGRANDE"."CONFIGURACION" ("ID") ENABLE,
	CONSTRAINT "ETAPA_PROCESO_FK" FOREIGN KEY ("IDPROCESO")
	 REFERENCES "MAIPOGRANDE"."PROCESO" ("IDPROCESO") ENABLE
   );