-- ****** Objeto: Tabla MAIPOGRANDE.EMPRESA Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."EMPRESA" 
   (	"RUTEMPRESA" VARCHAR2(10) NOT NULL ENABLE,
	"NOMBREEMPRESA" VARCHAR2(100) NOT NULL ENABLE,
	"DIRECCION" VARCHAR2(100) NOT NULL ENABLE,
	"REGION" NUMBER(*,0) NOT NULL ENABLE,
	"CIUDAD" VARCHAR2(50) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE,
	"TELEFONO" NUMBER(*,0) NOT NULL ENABLE,
	"CELULAR" NUMBER(*,0) NOT NULL ENABLE,
	"IDCOMUNA" NUMBER(*,0) NOT NULL ENABLE
   );