-- ****** Objeto: Tabla MAIPOGRANDE.MENU Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."MENU" 
   (	"IDMENU" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE,
	"SERVICIO" NUMBER(*,0) NOT NULL ENABLE,
	"URL" VARCHAR2(100),
	"ESTADO" CHAR(1) NOT NULL ENABLE,
	"IDPADRE" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "MENU_PK" PRIMARY KEY ("IDMENU") ENABLE,
	CONSTRAINT "MENU_MENU_FK" FOREIGN KEY ("IDPADRE")
	 REFERENCES "MAIPOGRANDE"."MENU" ("IDMENU") ENABLE
   );