-- ****** Objeto: Tabla MAIPOGRANDE.COMUNA Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."COMUNA" 
   (	"IDCOMUNA" NUMBER(*,0) NOT NULL ENABLE,
	"CODIGOCOMUNA" NUMBER(*,0) NOT NULL ENABLE,
	"IDREGION" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBRECOMUNA" VARCHAR2(100) NOT NULL ENABLE,
	"NOMBRECIUDAD" VARCHAR2(100) NOT NULL ENABLE,
	"NOMBREREGION" VARCHAR2(100) NOT NULL ENABLE,
	CONSTRAINT "COMUNA_PK" PRIMARY KEY ("IDCOMUNA") ENABLE
   );