-- ****** Objeto: Tabla MAIPOGRANDE.SUBASTA Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."SUBASTA" 
   (	"IDSUBASTA" NUMBER(*,0) NOT NULL ENABLE,
	"FECHASUBASTA" DATE NOT NULL ENABLE,
	"FECHATERMINO" DATE NOT NULL ENABLE,
	"ESTADO" CHAR(1) NOT NULL ENABLE,
	"IDPROCESO" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "SUBASTA_PK" PRIMARY KEY ("IDSUBASTA") ENABLE,
	CONSTRAINT "SUBASTA_PROCESO_FK" FOREIGN KEY ("IDPROCESO")
	 REFERENCES "MAIPOGRANDE"."PROCESO" ("IDPROCESO") ENABLE
   );