-- ****** Objeto: Tabla MAIPOGRANDE.PROCESO Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."PROCESO" 
   (	"IDPROCESO" NUMBER(*,0) NOT NULL ENABLE,
	"COMISION" NUMBER NOT NULL ENABLE,
	"VALORADUANA" NUMBER(*,0) NOT NULL ENABLE,
	"PAGOPORSERVICIO" NUMBER(*,0) NOT NULL ENABLE,
	"PAGOTRANSPORTISTA" NUMBER(*,0) NOT NULL ENABLE,
	"FECHAPROCESO" DATE NOT NULL ENABLE,
	"FECHAFINPROCESO" DATE NOT NULL ENABLE,
	"ESTADOPROCESO" VARCHAR2(20) NOT NULL ENABLE,
	"IDORDEN" NUMBER(*,0) NOT NULL ENABLE,
	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "PROCESO_PK" PRIMARY KEY ("IDPROCESO") ENABLE,
	CONSTRAINT "PROCESO_ADMINISTRADOR_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."ADMINISTRADOR" ("IDUSUARIO") ENABLE,
	CONSTRAINT "PROCESO_ORDEN_FK" FOREIGN KEY ("IDORDEN")
	 REFERENCES "MAIPOGRANDE"."ORDEN" ("IDORDEN") ENABLE
   );