-- ****** Objeto: Tabla MAIPOGRANDE.CLIENTEINTERNO Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."CLIENTEINTERNO" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBRECLIENTE" VARCHAR2(100) NOT NULL ENABLE,
	"RUTCLIENTE" VARCHAR2(20) NOT NULL ENABLE,
	"IDCOMUNA" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "CLIENTEINTERNO_PK" PRIMARY KEY ("IDUSUARIO") ENABLE,
	CONSTRAINT "CLIENTEINTERNO_COMUNA_FK" FOREIGN KEY ("IDCOMUNA")
	 REFERENCES "MAIPOGRANDE"."COMUNA" ("IDCOMUNA") ENABLE,
	CONSTRAINT "CLIENTEINTERNO_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."USUARIO" ("IDUSUARIO") ENABLE
   );