-- ****** Objeto: Tabla MAIPOGRANDE.DETALLESUBASTA Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."DETALLESUBASTA" 
   (	"IDDETALLE" NUMBER(*,0) NOT NULL ENABLE,
	"MONTOOFERTA" NUMBER(*,0) NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE,
	"ESTADO" VARCHAR2(10) NOT NULL ENABLE,
	"IDSUBASTA" NUMBER(*,0) NOT NULL ENABLE,
	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "DETALLESUBASTA_PK" PRIMARY KEY ("IDDETALLE") ENABLE,
	CONSTRAINT "DETALLESUBASTA_SUBASTA_FK" FOREIGN KEY ("IDSUBASTA")
	 REFERENCES "MAIPOGRANDE"."SUBASTA" ("IDSUBASTA") ENABLE,
	CONSTRAINT "DETALLESUBASTA_TRANS_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."TRANSPORTISTA" ("IDUSUARIO") ENABLE
   );