-- ****** Objeto: Tabla MAIPOGRANDE.LOGTRACE Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."LOGTRACE" 
   (	"LOGID" NUMBER(*,0) NOT NULL ENABLE,
	"SERVICIO" VARCHAR2(100) NOT NULL ENABLE,
	"SUBSERVICIO" VARCHAR2(100) NOT NULL ENABLE,
	"ENTRADA" CLOB NOT NULL ENABLE,
	"SALIDA" CLOB NOT NULL ENABLE,
	"FECHA" DATE NOT NULL ENABLE,
	"ESTADO" VARCHAR2(10) NOT NULL ENABLE,
	"IDSESION" VARCHAR2(100) NOT NULL ENABLE,
	CONSTRAINT "LOGTRACE_PK" PRIMARY KEY ("LOGID") ENABLE,
	CONSTRAINT "LOGTRACE_SESION_FK" FOREIGN KEY ("IDSESION")
	 REFERENCES "MAIPOGRANDE"."SESION" ("IDSESION") ENABLE
   );