-- ****** Objeto: Tabla MAIPOGRANDE.ORDEN Fecha de Script: 07-10-2020 20:17:46 ******
  CREATE TABLE "MAIPOGRANDE"."ORDEN" 
   (	"IDORDEN" NUMBER(*,0) NOT NULL ENABLE,
	"FECHAORDEN" DATE NOT NULL ENABLE,
	"FIRMACONTRATO" CHAR(1) NOT NULL ENABLE,
	"FECHAFIRMACONTRATO" DATE,
	"ESTADO" VARCHAR2(20) NOT NULL ENABLE,
	"PRECIOVENTA" NUMBER(*,0) NOT NULL ENABLE,
	"IDCLIENTEEXTERNO" NUMBER(*,0),
	"IDCLIENTEINTERNO" NUMBER(*,0),
	CONSTRAINT "ORDEN_PK" PRIMARY KEY ("IDORDEN") ENABLE,
	CONSTRAINT "ORDEN_CLIENTEEXTERNO_FK" FOREIGN KEY ("IDCLIENTEEXTERNO")
	 REFERENCES "MAIPOGRANDE"."CLIENTEEXTERNO" ("IDUSUARIO") ENABLE,
	CONSTRAINT "ORDEN_CLIENTEINTERNO_FK" FOREIGN KEY ("IDCLIENTEINTERNO")
	 REFERENCES "MAIPOGRANDE"."CLIENTEINTERNO" ("IDUSUARIO") ENABLE
   );