-- ****** Objeto: Tabla MAIPOGRANDE.DETALLEORDEN Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."DETALLEORDEN" 
   (	"CANTIDAD" NUMBER(*,0) NOT NULL ENABLE,
	"IDORDEN" NUMBER(*,0) NOT NULL ENABLE,
	"MONTO" NUMBER(*,0) NOT NULL ENABLE,
	"IDCATEGORIA" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "DETALLEORDEN_CATEGORIA_FK" FOREIGN KEY ("IDCATEGORIA")
	 REFERENCES "MAIPOGRANDE"."CATEGORIA" ("IDCATEGORIA") ENABLE,
	CONSTRAINT "DETALLEORDEN_ORDEN_FK" FOREIGN KEY ("IDORDEN")
	 REFERENCES "MAIPOGRANDE"."ORDEN" ("IDORDEN") ENABLE
   );