-- ****** Objeto: Tabla MAIPOGRANDE.CLIENTEEXTERNO Fecha de Script: 07-10-2020 21:52:07 ******
  CREATE TABLE "MAIPOGRANDE"."CLIENTEEXTERNO" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBREEMPRESA" VARCHAR2(100) NOT NULL ENABLE,
	"PAIS" VARCHAR2(20) NOT NULL ENABLE,
	"CIUDAD" VARCHAR2(100),
	CONSTRAINT "CLIENTEEXTERNO_PK" PRIMARY KEY ("IDUSUARIO") ENABLE,
	CONSTRAINT "CLIENTEEXTERNO_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."USUARIO" ("IDUSUARIO") ENABLE
   );