-- ****** Objeto: Tabla MAIPOGRANDE.CONFIGURACION Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."CONFIGURACION" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBREPASO" VARCHAR2(100) NOT NULL ENABLE,
	"TIPO" VARCHAR2(10) NOT NULL ENABLE,
	"IDANTERIOR" NUMBER(*,0),
	"IDPOSTERIOR" NUMBER(*,0),
	CONSTRAINT "CONFIGURACION_PK" PRIMARY KEY ("ID") ENABLE
   );