-- ****** Objeto: Tabla MAIPOGRANDE.SESION Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."SESION" 
   (	"IDSESION" VARCHAR2(100) NOT NULL ENABLE,
	"REMOTE_ADDR" VARCHAR2(100) NOT NULL ENABLE,
	"FECHA" VARCHAR2(20) NOT NULL ENABLE,
	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "SESION_PK" PRIMARY KEY ("IDSESION") ENABLE,
	CONSTRAINT "SESION_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."USUARIO" ("IDUSUARIO") ENABLE
   );