-- ****** Objeto: Tabla MAIPOGRANDE.TRANSPORTISTA Fecha de Script: 28-09-2020 16:13:30 ******
  CREATE TABLE "MAIPOGRANDE"."TRANSPORTISTA" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE,
	"NOMBRETRANSPORTISTA" VARCHAR2(100) NOT NULL ENABLE,
	"RUTTRANSPORTISTA" VARCHAR2(20) NOT NULL ENABLE,
	"FIRMACONTRATO" CHAR(1) NOT NULL ENABLE,
	"FECHATERMINO" DATE NOT NULL ENABLE,
	"IDCOMUNA" NUMBER(*,0) NOT NULL ENABLE,
	CONSTRAINT "TRANSPORTISTA_PK" PRIMARY KEY ("IDUSUARIO") ENABLE,
	CONSTRAINT "TRANSPORTISTA_COMUNA_FK" FOREIGN KEY ("IDCOMUNA")
	 REFERENCES "MAIPOGRANDE"."COMUNA" ("IDCOMUNA") ENABLE,
	CONSTRAINT "TRANSPORTISTA_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	 REFERENCES "MAIPOGRANDE"."USUARIO" ("IDUSUARIO") ENABLE
   );