-- ****** Objeto: Paquete MAIPOGRANDE.PKG_PERFIL Fecha de Script: 19-10-2020 23:07:01 ******
CREATE OR REPLACE PACKAGE "MAIPOGRANDE"."PKG_PERFIL" AS
PROCEDURE SP_CREAR(
  P_NOMBREPERFIL 			IN VARCHAR2,
  P_CODIGOPERFIL 			IN VARCHAR2,
  P_SERVICIOPERFIL 		IN VARCHAR2,
  P_IDPERFIL 			    OUT NUMBER,
  P_ESTADO 		        OUT NUMBER,
  P_GLOSA 	          OUT VARCHAR2
);

PROCEDURE SP_ELIMINAR (
  P_IDPERFIL IN NUMBER,
  P_ESTADO OUT NUMBER,
  P_GLOSA OUT VARCHAR2
);

PROCEDURE SP_MODIFICAR (
P_IDPERFIL IN NUMBER,
P_NOMBREPERFIL IN VARCHAR2,
P_CODIGOPERFIL IN VARCHAR2,
P_SERVICIOPERFIL IN VARCHAR2,
P_ESTADOPERFIL IN NUMBER,
P_ESTADO  OUT NUMBER,
P_GLOSA OUT VARCHAR2
);

END "PKG_PERFIL";
